micronaut:
  application:
    name: awsFunctionGraalvmDatabaseH2Postgres
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://godadb.cm2x02yvro84.ap-south-1.rds.amazonaws.com:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:12345678}
jpa:
  default:
    packages-to-scan:
      - 'aws.function.graalvm.database.h2.postgres'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
goda:
  sameName: "Goda"